kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: node:24
    commands:
      - npm install --legacy-peer-deps
      - npm run test || echo "No tests found"

  - name: build-docker
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t my-react-app .

  - name: deploy
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker stop my-react-app || true
      - docker rm my-react-app || true
      - docker run -d -p 3005:3005 --name my-react-app my-react-app

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
